# Generated by Django 4.2.5 on 2023-09-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team", models.CharField(max_length=30)),
                ("date", models.CharField(max_length=10)),
                ("opponent", models.CharField(max_length=30)),
                ("time", models.CharField(max_length=10)),
                ("channel", models.CharField(max_length=100)),
            ],
        ),
    ]
